### ISSUE TITLE
Khòaⁿ jī-tián看字典 502

### ISSUE THREAD

**Issue by a8568730** [miau715/POJTest#1]
![圖片](https://user-images.githubusercontent.com/6355592/165213063-280869b8-377e-4552-8b7c-14937dcda47e.png)

Khòaⁿ jī-tián tiám--loeh 502.
![圖片](https://user-images.githubusercontent.com/6355592/165213092-cd9f4f09-a171-4cbe-811c-7890dd6777b0.png)

**Comment by miau715** [comment]
Lí hó, che sī Moedict bāng-chām chhut būn-tê, góa sī liâm khì in hia niâ, bô hoat-tō͘ chhú-lí in ê būn-tê, ài tán in siu-lí. Chit-má khòaⁿ-khí-lâi sī ti̍t-chiap liâm khì hia ê ia̍h-bīn lóng 502, m̄-koán sī Hôa-gí ia̍h-sī Tâi-gí lóng kāng-khoán. 
Ex: Iōng "[https://www.moedict.tw/萌](https://www.moedict.tw/萌)" liâm, mā-sī 502.
